In [5]:
%load_ext autoreload
%autoreload 2

import numpy as np
from utils_table_generator import *

wandb_username = "gbg141"  # Change this to your W&B username if needed
wandb_project = "Proteo"  # Change this to your W&B project name if needed
metric = "mae"  # Change this to the metric you want to extract (e.g., "mae", "mse", etc.)
original_units = True  # Set to True if you want to convert back to original units
csv_filename = "proteo_results.csv"  # Output CSV filename
save_csv = False  # Set to True if you want to save the grouped results to a CSV file

df = load_results_dataframe(wandb_username, wandb_project, original_units=original_units, metric=metric, csv_filename=csv_filename)
df, grouped, best_configs, summary, table = generate_table(df, save_csv=save_csv, csv_filename=csv_filename)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
▶ After building df, df.shape = (4704, 170)
▶ hyperparam_cols = ['dataset.dataloader_params.batch_size', 'dataset.loader.parameters.adj_thresh', 'model.backbone._target_', 'model.backbone.act', 'model.backbone.hidden_channels', 'model.backbone.in_channels', 'model.backbone_wrapper._target_', 'model.backbone_wrapper.out_channels', 'model.backbone_wrapper.wrapper_name', 'model.feature_encoder._target_', 'model.feature_encoder.encoder_name', 'model.feature_encoder.in_channels', 'model.feature_encoder.out_channels', 'model.readout.fc_act', 'model.readout.fc_dim', 'model.readout.fc_input_dim', 'model.readout.graph_encoder_dim', 'model.readout.hidden_dim', 'model.readout.in_channels', 'model/params/total', 'model/params/trainable', 'optimizer.parameters.lr', 'trainer.devices']
▶ group_cols = ['dataset', 'model', 'dataset.dataloader_params.batch_size', 'dataset.loader.parameters.adj_thresh', 'model.backbone._target_', 'model.backbone.act', 'model.backbone.hidden_channels', 'model.backbone.in_channels', 'model.backbone_wrapper._target_', 'model.backbone_wrapper.out_channels', 'model.backbone_wrapper.wrapper_name', 'model.feature_encoder._target_', 'model.feature_encoder.encoder_name', 'model.feature_encoder.in_channels', 'model.feature_encoder.out_channels', 'model.readout.fc_act', 'model.readout.fc_dim', 'model.readout.fc_input_dim', 'model.readout.graph_encoder_dim', 'model.readout.hidden_dim', 'model.readout.in_channels', 'model/params/total', 'model/params/trainable', 'optimizer.parameters.lr', 'trainer.devices']
▶ After grouping, grouped.shape = (767, 28)
▶ best_configs.shape = (6, 28)

/home/gbg141/TopoProteo/tutorials/utils_table_generator.py:101: DtypeWarning: Columns (23,40,156,161,164,166,168,169) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_filename)
/home/gbg141/TopoProteo/tutorials/utils_table_generator.py:206: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].apply(ensure_hashable)

▶ df_best_runs.shape (should be #datasets × #models × #folds) = (22, 29)
▶ summary.shape = (6, 4)
▶ final_table.shape = (6, 27)
| dataset              | model   |   dataset.dataloader_params.batch_size |   dataset.loader.parameters.adj_thresh | model.backbone._target_       | model.backbone.act   | model.backbone.hidden_channels   |   model.backbone.in_channels | model.backbone_wrapper._target_       | model.backbone_wrapper.out_channels   | model.backbone_wrapper.wrapper_name   | model.feature_encoder._target_              | model.feature_encoder.encoder_name   | model.feature_encoder.in_channels   |   model.feature_encoder.out_channels | model.readout.fc_act   | model.readout.fc_dim   | model.readout.fc_input_dim   | model.readout.graph_encoder_dim   |   model.readout.hidden_dim | model.readout.in_channels   |   model/params/total |   model/params/trainable |   optimizer.parameters.lr | trainer.devices   |   mean_test_mae |   std_test_mae |
|:---------------------|:--------|---------------------------------------:|---------------------------------------:|:------------------------------|:---------------------|:---------------------------------|-----------------------------:|:--------------------------------------|:--------------------------------------|:--------------------------------------|:--------------------------------------------|:-------------------------------------|:------------------------------------|-------------------------------------:|:-----------------------|:-----------------------|:-----------------------------|:----------------------------------|---------------------------:|:----------------------------|---------------------:|-------------------------:|--------------------------:|:------------------|----------------:|---------------:|
| spearman_correlation | GATv4   |                                      1 |                                 0.6000 | topobench.nn.backbones.GATv4  | tanh                 | [8, 16]                          |                       8.0000 | topobench.nn.wrappers.GATv4Wrapper    | [8, 16]                               | GATv4Wrapper                          | topobench.nn.encoders.AllCellFeatureEncoder | AllCellFeatureEncoder                | [1]                                 |                                    8 | tanh                   | [128, 64, 32]          | [8, 16]                      | 256                               |                      21774 | [8, 16]                     |              5682078 |                  5682078 |                    0.0001 | [1]               |          9.8449 |       nan      |
| spearman_correlation | gcn     |                                     32 |                                 0.6000 | torch_geometric.nn.models.GCN | tanh                 | 4.0                              |                       4.0000 | topobench.nn.wrappers.GNNWrapper      | 4                                     | GNNWrapper                            | topobench.nn.encoders.AllCellFeatureEncoder | AllCellFeatureEncoder                | [1]                                 |                                    4 | tanh                   | [256, 128, 64]         | 4                            | 128                               |                      29032 | 4.0                         |              3868866 |                  3868866 |                    0.0010 | [4]               |          6.5974 |         2.7365 |
| spearman_correlation | mlp     |                                     16 |                                 0.6000 | torch.nn.Identity             | nan                  | nan                              |                     nan      | topobench.nn.wrappers.IdentityWrapper | 1                                     | IdentityWrapper                       | topobench.nn.encoders.IdentityEncoder       | IdentityEncoder                      | 1                                   |                                    1 | tanh                   | [128, 64, 32]          | 1                            | [512, 256]                        |                       7258 | nan                         |              3924190 |                  3924190 |                    0.0010 | [6]               |          5.7938 |         1.9047 |
| wgcna                | GATv4   |                                      1 |                                 0.2000 | topobench.nn.backbones.GATv4  | tanh                 | [8, 16]                          |                       8.0000 | topobench.nn.wrappers.GATv4Wrapper    | [8, 16]                               | GATv4Wrapper                          | topobench.nn.encoders.AllCellFeatureEncoder | AllCellFeatureEncoder                | [1]                                 |                                    8 | tanh                   | [128, 64, 32]          | [8, 16]                      | 128                               |                      21774 | [8, 16]                     |              2878494 |                  2878494 |                    0.0001 | [3]               |         10.1966 |       nan      |
| wgcna                | gcn     |                                      8 |                                 0.2000 | torch_geometric.nn.models.GCN | relu                 | 4.0                              |                       4.0000 | topobench.nn.wrappers.GNNWrapper      | 4                                     | GNNWrapper                            | topobench.nn.encoders.AllCellFeatureEncoder | AllCellFeatureEncoder                | [1]                                 |                                    4 | tanh                   | [256, 128, 64]         | 4                            | 128                               |                      29032 | 4.0                         |              3868866 |                  3868866 |                    0.0010 | [5]               |          6.3792 |         2.2344 |
| wgcna                | mlp     |                                     16 |                                 0.2000 | torch.nn.Identity             | nan                  | nan                              |                     nan      | topobench.nn.wrappers.IdentityWrapper | 1                                     | IdentityWrapper                       | topobench.nn.encoders.IdentityEncoder       | IdentityEncoder                      | 1                                   |                                    1 | tanh                   | [128, 64, 32]          | 1                            | [512, 256]                        |                       7258 | nan                         |              3924190 |                  3924190 |                    0.0010 | [7]               |          5.7938 |         1.9047 |

=== Test‐mae (mean ± std) with models as rows, datasets as columns ===

| dataset              | GATv4         | gcn             | mlp             |
|:---------------------|:--------------|:----------------|:----------------|
| spearman_correlation | 9.8449 ± nan  | 6.5974 ± 2.7365 | 5.7938 ± 1.9047 |
| wgcna                | 10.1966 ± nan | 6.3792 ± 2.2344 | 5.7938 ± 1.9047 |

/home/gbg141/TopoProteo/tutorials/utils_table_generator.py:263: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["config_key"]          = df.apply(lambda r: make_config_key(r, grouped_cols), axis=1)

In [33]:
summary

                dataset  model  mean_test_mae  std_test_mae          mean_std
0  spearman_correlation  GATv4      26.057519           NaN     26.0575 ± nan
1  spearman_correlation    gcn      21.718422      2.298666  21.7184 ± 2.2987
2  spearman_correlation    mlp      22.039730      2.471869  22.0397 ± 2.4719
3                 wgcna  GATv4      29.409528           NaN     29.4095 ± nan
4                 wgcna    gcn      21.086643      2.396164  21.0866 ± 2.3962
5                 wgcna    mlp      22.039730      2.471869  22.0397 ± 2.4719

In [34]:
best_configs

,dataset,model,dataset.dataloader_params.batch_size,dataset.loader.parameters.adj_thresh,model.backbone._target_,model.backbone.act,model.backbone.hidden_channels,model.backbone.in_channels,model.backbone_wrapper._target_,model.backbone_wrapper.out_channels,...,model.readout.hidden_dim,model.readout.in_channels,model/params/total,model/params/trainable,optimizer.parameters.lr,trainer.devices,mean_val_mae,std_val_mae,n_folds,config_key
0,spearman_correlation,GATv4,1,0.6,topobench.nn.backbones.GATv4,tanh,"[8, 16]",8.0,topobench.nn.wrappers.GATv4Wrapper,"[8, 16]",...,21774,"[8, 16]",2878494,2878494,0.0001,[1],26.057519,NaN,1,"(spearman_correlation, GATv4, 1, 0.6, topobenc..."
1,spearman_correlation,gcn,8,0.6,torch_geometric.nn.models.GCN,tanh,4.0,4.0,topobench.nn.wrappers.GNNWrapper,4,...,29032,4.0,3868866,3868866,0.0001,[4],21.718422,2.298666,5,"(spearman_correlation, gcn, 8, 0.6, torch_geom..."
2,spearman_correlation,mlp,8,0.6,torch.nn.Identity,NaN,NaN,NaN,topobench.nn.wrappers.IdentityWrapper,1,...,7258,NaN,6022110,6022110,0.0001,[6],22.039730,2.471869,5,"(spearman_correlation, mlp, 8, 0.6, torch.nn.I..."
3,wgcna,GATv4,1,0.2,topobench.nn.backbones.GATv4,tanh,"[8, 16]",8.0,topobench.nn.wrappers.GATv4Wrapper,"[8, 16]",...,21774,"[8, 16]",5682078,5682078,0.0001,[3],29.409528,NaN,1,"(wgcna, GATv4, 1, 0.2, topobench.nn.backbones...."
4,wgcna,gcn,8,0.3,torch_geometric.nn.models.GCN,tanh,4.0,4.0,topobench.nn.wrappers.GNNWrapper,4,...,29032,4.0,3868866,3868866,0.0001,[5],21.086643,2.396164,5,"(wgcna, gcn, 8, 0.3, torch_geometric.nn.models..."
5,wgcna,mlp,8,0.2,torch.nn.Identity,NaN,NaN,NaN,topobench.nn.wrappers.IdentityWrapper,1,...,7258,NaN,6022110,6022110,0.0001,[7],22.039730,2.471869,5,"(wgcna, mlp, 8, 0.2, torch.nn.Identity, nan, n..."

In [35]:
best_configs["config_key"][5]

('wgcna',
 'mlp',
 8,
 0.2,
 'torch.nn.Identity',
 nan,
 nan,
 nan,
 'topobench.nn.wrappers.IdentityWrapper',
 1,
 'IdentityWrapper',
 'topobench.nn.encoders.IdentityEncoder',
 'IdentityEncoder',
 '1',
 1,
 'tanh',
 '[1024, 1024, 512, 256]',
 1,
 '[512, 256]',
 7258,
 nan,
 6022110,
 6022110,
 0.0001,
 '[7]')

In [23]:
best_configs["config_key"][5]

('wgcna',
 'mlp',
 8,
 0.2,
 'torch.nn.Identity',
 nan,
 nan,
 nan,
 'topobench.nn.wrappers.IdentityWrapper',
 1,
 'IdentityWrapper',
 'topobench.nn.encoders.IdentityEncoder',
 'IdentityEncoder',
 '1',
 1,
 'tanh',
 '[1024, 1024, 512, 256]',
 1,
 '[512, 256]',
 7258,
 nan,
 6022110,
 6022110,
 0.0001,
 '[7]')

In [36]:
best_configs["config_key"][2]

('spearman_correlation',
 'mlp',
 8,
 0.6,
 'torch.nn.Identity',
 nan,
 nan,
 nan,
 'topobench.nn.wrappers.IdentityWrapper',
 1,
 'IdentityWrapper',
 'topobench.nn.encoders.IdentityEncoder',
 'IdentityEncoder',
 '1',
 1,
 'tanh',
 '[1024, 1024, 512, 256]',
 1,
 '[512, 256]',
 7258,
 nan,
 6022110,
 6022110,
 0.0001,
 '[6]')