# Results table generator

In [11]:
%load_ext autoreload
%autoreload 2

import numpy as np
from utils_table_generator import *

wandb_username = "lcornelis"#"gbg141"#"lcornelis"  # Change this to your W&B username if needed
wandb_project = "Proteo_new_variable_stratified_filtered_gatv4_gat" #"TopoProteoGatV4"#"ProteoBaselines"  # Change this to your W&B project name if needed
metric = "mse"  # Change this to the metric you want to extract (e.g., "mae", "mse", etc.)
original_units = True  # Set to True if you want to convert back to original units
csv_filename = wandb_project+"_"+wandb_username+"_"+"results.csv"  # Output CSV filename
force_load = False
save_csv = False  # Set to True if you want to save the grouped results to a CSV file

df = load_results_dataframe(wandb_username, wandb_project, original_units=original_units, metric=metric, force_load=force_load, csv_filename=csv_filename)
df, grouped, best_configs, summary, table = generate_table(df, save_csv=save_csv, csv_filename=csv_filename)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
▶ Number of runs fetched from W&B: 1562

FileNotFoundError: [Errno 2] No such file or directory: '/scratch/lcornelis/data/data_louisa/FTD/processed/FTD_y_val_cog_z_score_wgcna_adj_thresh_0.2_num_nodes_3667_mutation_GRN,MAPT,C9orf72,CTL_csf_sex_M,F_train_random_state_42_5fold_0.json'

In [10]:
best_configs

,dataset,model,dataset.dataloader_params.batch_size,model.readout.fc_dim,model.readout.fc_dropout,model.readout.feature_encoder_dim,model.readout.graph_encoder_dim,model/params/total,model/params/trainable,optimizer.parameters.lr,optimizer.parameters.weight_decay,trainer.devices,mean_val_mae,std_val_mae,n_folds,config_key
16,pointcloud,mlp,8,"[128, 32, 16]",0.1,4,"[64, 16]",246439,246439,0.01,0.0001,[7],0.084417,0.011267,5,"(pointcloud, mlp, 8, [128, 32, 16], 0.1, 4, [6..."

In [6]:
grouped

,dataset,model,dataset.dataloader_params.batch_size,model.readout.fc_act,model.readout.fc_dim,model.readout.fc_dropout,model.readout.feature_encoder_dim,model.readout.graph_encoder_dim,model/params/total,model/params/trainable,optimizer.parameters.lr,optimizer.parameters.weight_decay,trainer.devices,mean_val_mae,std_val_mae,n_folds
0,pointcloud,mlp,8,relu,"[128, 32, 16]",0.1,4,"[128, 32]",486455,486455,0.001,0.0000,[0],0.094792,0.017551,5
1,pointcloud,mlp,8,relu,"[128, 32, 16]",0.1,4,"[128, 32]",486455,486455,0.001,0.0001,[3],0.093318,0.017082,5
2,pointcloud,mlp,8,relu,"[128, 32, 16]",0.1,4,"[128, 32]",486455,486455,0.001,0.0010,[2],0.090287,0.017491,5
3,pointcloud,mlp,8,relu,"[128, 32, 16]",0.1,4,"[128, 32]",486455,486455,0.010,0.0000,[4],0.091011,0.014465,5
4,pointcloud,mlp,8,relu,"[128, 32, 16]",0.1,4,"[128, 32]",486455,486455,0.010,0.0001,[7],0.085740,0.013660,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2797,pointcloud,mlp,64,tanh,"[64, 32, 16]",0.3,16,"[64, 16]",243303,243303,0.001,0.0001,[3],0.120990,0.005197,5
2798,pointcloud,mlp,64,tanh,"[64, 32, 16]",0.3,16,"[64, 16]",243303,243303,0.001,0.0010,[2],0.120213,0.005445,5
2799,pointcloud,mlp,64,tanh,"[64, 32, 16]",0.3,16,"[64, 16]",243303,243303,0.010,0.0000,[5],0.121013,0.010806,5
2800,pointcloud,mlp,64,tanh,"[64, 32, 16]",0.3,16,"[64, 16]",243303,243303,0.010,0.0001,[7],0.108877,0.014909,5
2801,pointcloud,mlp,64,tanh,"[64, 32, 16]",0.3,16,"[64, 16]",243303,243303,0.010,0.0010,[6],0.121976,0.011585,5

In [7]:
best_configs.iloc[1]

IndexError: single positional indexer is out-of-bounds

In [6]:
best_configs

,dataset,model,dataset.dataloader_params.batch_size,dataset.loader.parameters.adj_thresh,model.backbone._target_,model.backbone.act,model.backbone.attn_type,model.backbone.dropout,model.backbone.heads,model.backbone.hidden_channels,...,model/params/trainable,optimizer.parameters.lr,optimizer.parameters.weight_decay,paths.root_dir,paths.work_dir,trainer.devices,mean_val_mae,std_val_mae,n_folds,config_key
620,pointcloud,mlp,32,1.00,torch.nn.Identity,NaN,NaN,NaN,NaN,NaN,...,480071,0.010,0.001,/home/lcornelis/code/TopoProteo,/home/lcornelis/code/TopoProteo,[6],0.083961,0.015639,5,"(pointcloud, mlp, 32, 1.0, torch.nn.Identity, ..."
1532,wgcna,GPS,8,1.00,topobench.nn.backbones.GPSEncoder,NaN,performer,0.4,4.0,NaN,...,517545,0.001,0.000,/home/gbg141/TopoProteo,/home/gbg141/TopoProteo,[7],0.113155,0.008814,5,"(wgcna, GPS, 8, 1.0, topobench.nn.backbones.GP..."
1764,wgcna,gat,8,0.15,torch_geometric.nn.models.GAT,relu,NaN,0.1,4.0,8.0,...,968997,0.001,0.001,/home/gbg141/TopoProteo,/home/gbg141/TopoProteo,[3],0.095066,0.013228,5,"(wgcna, gat, 8, 0.15, torch_geometric.nn.model..."
2793,wgcna,gcn,8,0.30,torch_geometric.nn.models.GCN,relu,NaN,0.1,NaN,8.0,...,499301,0.001,0.001,/home/gbg141/TopoProteo,/home/gbg141/TopoProteo,[7],0.090204,0.008956,5,"(wgcna, gcn, 8, 0.3, torch_geometric.nn.models..."

In [23]:
best_configs["config_key"][5]

('wgcna',
 'mlp',
 8,
 0.2,
 'torch.nn.Identity',
 nan,
 nan,
 nan,
 'topobench.nn.wrappers.IdentityWrapper',
 1,
 'IdentityWrapper',
 'topobench.nn.encoders.IdentityEncoder',
 'IdentityEncoder',
 '1',
 1,
 'tanh',
 '[1024, 1024, 512, 256]',
 1,
 '[512, 256]',
 7258,
 nan,
 6022110,
 6022110,
 0.0001,
 '[7]')

In [36]:
best_configs["config_key"][2]

('spearman_correlation',
 'mlp',
 8,
 0.6,
 'torch.nn.Identity',
 nan,
 nan,
 nan,
 'topobench.nn.wrappers.IdentityWrapper',
 1,
 'IdentityWrapper',
 'topobench.nn.encoders.IdentityEncoder',
 'IdentityEncoder',
 '1',
 1,
 'tanh',
 '[1024, 1024, 512, 256]',
 1,
 '[512, 256]',
 7258,
 nan,
 6022110,
 6022110,
 0.0001,
 '[6]')