# Results table generator

In [2]:
%load_ext autoreload
%autoreload 2

import numpy as np
from utils_table_generator import *

wandb_username = "lcornelis"#"gbg141"#"lcornelis"  # Change this to your W&B username if needed
wandb_project = "Proteo_new_variable_stratified_filtered" #"TopoProteoGatV4"#"ProteoBaselines"  # Change this to your W&B project name if needed
metric = "mse"  # Change this to the metric you want to extract (e.g., "mae", "mse", etc.)
original_units = True  # Set to True if you want to convert back to original units
csv_filename = wandb_project+"_"+wandb_username+"_"+"results.csv"  # Output CSV filename
force_load = False
save_csv = False  # Set to True if you want to save the grouped results to a CSV file

df = load_results_dataframe(wandb_username, wandb_project, original_units=original_units, metric=metric, force_load=force_load, csv_filename=csv_filename)
df, grouped, best_configs, summary, table = generate_table(df, save_csv=save_csv, csv_filename=csv_filename)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
▶ Number of runs fetched from W&B: 64997
▶ After building df, df.shape = (64861, 186)
▶ hyperparam_cols = ['dataset.dataloader_params.batch_size', 'dataset.loader.parameters.adj_thresh', 'model.backbone._target_', 'model.backbone.act', 'model.backbone.attn_type', 'model.backbone.dropout', 'model.backbone.heads', 'model.backbone.hidden_channels', 'model.backbone.hidden_dim', 'model.backbone.in_channels', 'model.backbone.input_dim', 'model.backbone.num_layers', 'model.backbone_wrapper._target_', 'model.backbone_wrapper.out_channels', 'model.backbone_wrapper.wrapper_name', 'model.feature_encoder._target_', 'model.feature_encoder.encoder_name', 'model.feature_encoder.in_channels', 'model.feature_encoder.out_channels', 'model.feature_encoder.proj_dropout', 'model.readout.fc_act', 'model.readout.fc_dim', 'model.readout.fc_dropout', 'model.readout.fc_input_dim', 'model.readout.feature_encoder_dim', 'model.readout.graph_encoder_dim', 'model.readout.hidden_dim', 'model.readout.in_channels', 'model.readout.use_features', 'model/params/total', 'model/params/trainable', 'optimizer.parameters.lr', 'optimizer.parameters.weight_decay', 'paths.root_dir', 'paths.work_dir', 'trainer.devices']
▶ group_cols = ['dataset', 'model', 'dataset.dataloader_params.batch_size', 'dataset.loader.parameters.adj_thresh', 'model.backbone._target_', 'model.backbone.act', 'model.backbone.attn_type', 'model.backbone.dropout', 'model.backbone.heads', 'model.backbone.hidden_channels', 'model.backbone.hidden_dim', 'model.backbone.in_channels', 'model.backbone.input_dim', 'model.backbone.num_layers', 'model.backbone_wrapper._target_', 'model.backbone_wrapper.out_channels', 'model.backbone_wrapper.wrapper_name', 'model.feature_encoder._target_', 'model.feature_encoder.encoder_name', 'model.feature_encoder.in_channels', 'model.feature_encoder.out_channels', 'model.feature_encoder.proj_dropout', 'model.readout.fc_act', 'model.readout.fc_dim', 'model.readout.fc_dropout', 'model.readout.fc_input_dim', 'model.readout.feature_encoder_dim', 'model.readout.graph_encoder_dim', 'model.readout.hidden_dim', 'model.readout.in_channels', 'model.readout.use_features', 'model/params/total', 'model/params/trainable', 'optimizer.parameters.lr', 'optimizer.parameters.weight_decay', 'paths.root_dir', 'paths.work_dir', 'trainer.devices']
▶ After grouping, grouped.shape = (8426, 41)
▶ best_configs.shape = (4, 41)
▶ df_best_runs.shape (should be #datasets × #models × #folds) = (20, 42)
▶ summary.shape = (4, 4)
▶ final_table.shape = (4, 40)
| dataset    | model   |   dataset.dataloader_params.batch_size |   dataset.loader.parameters.adj_thresh | model.backbone._target_           | model.backbone.act   | model.backbone.attn_type   |   model.backbone.dropout |   model.backbone.heads |   model.backbone.hidden_channels |   model.backbone.hidden_dim |   model.backbone.in_channels |   model.backbone.input_dim |   model.backbone.num_layers | model.backbone_wrapper._target_       |   model.backbone_wrapper.out_channels | model.backbone_wrapper.wrapper_name   | model.feature_encoder._target_              | model.feature_encoder.encoder_name   | model.feature_encoder.in_channels   |   model.feature_encoder.out_channels |   model.feature_encoder.proj_dropout | model.readout.fc_act   | model.readout.fc_dim   |   model.readout.fc_dropout |   model.readout.fc_input_dim |   model.readout.feature_encoder_dim | model.readout.graph_encoder_dim   |   model.readout.hidden_dim |   model.readout.in_channels |   model.readout.use_features |   model/params/total |   model/params/trainable |   optimizer.parameters.lr |   optimizer.parameters.weight_decay | paths.root_dir                  | paths.work_dir                  | trainer.devices   |   mean_test_mae |   std_test_mae |
|:-----------|:--------|---------------------------------------:|---------------------------------------:|:----------------------------------|:---------------------|:---------------------------|-------------------------:|-----------------------:|---------------------------------:|----------------------------:|-----------------------------:|---------------------------:|----------------------------:|:--------------------------------------|--------------------------------------:|:--------------------------------------|:--------------------------------------------|:-------------------------------------|:------------------------------------|-------------------------------------:|-------------------------------------:|:-----------------------|:-----------------------|---------------------------:|-----------------------------:|------------------------------------:|:----------------------------------|---------------------------:|----------------------------:|-----------------------------:|---------------------:|-------------------------:|--------------------------:|------------------------------------:|:--------------------------------|:--------------------------------|:------------------|----------------:|---------------:|
| pointcloud | mlp     |                                     32 |                                 1.0000 | torch.nn.Identity                 | nan                  | nan                        |                 nan      |               nan      |                         nan      |                    nan      |                     nan      |                   nan      |                    nan      | topobench.nn.wrappers.IdentityWrapper |                                     1 | IdentityWrapper                       | topobench.nn.encoders.IdentityEncoder       | IdentityEncoder                      | 1                                   |                                    1 |                             nan      | tanh                   | (64, 32, 16)           |                     0.1000 |                            1 |                                  16 | (128, 32)                         |                       3667 |                    nan      |                       1.0000 |               485399 |                   485399 |                    0.0100 |                              0.0010 | /home/lcornelis/code/TopoProteo | /home/lcornelis/code/TopoProteo | (6,)              |          0.0802 |         0.0135 |
| wgcna      | GPS     |                                      8 |                                 1.0000 | topobench.nn.backbones.GPSEncoder | nan                  | performer                  |                   0.4000 |                 2.0000 |                         nan      |                      8.0000 |                     nan      |                     8.0000 |                      2.0000 | topobench.nn.wrappers.GNNWrapper      |                                     8 | GNNWrapper                            | topobench.nn.encoders.AllCellFeatureEncoder | AllCellFeatureEncoder                | (21,)                               |                                    8 |                               0.2000 | tanh                   | (16, 8, 4)             |                     0.1000 |                            8 |                                   4 | 16                                |                      29336 |                      8.0000 |                       0.0000 |               508585 |                   508585 |                    0.0100 |                              0.0000 | /home/gbg141/TopoProteo         | /home/gbg141/TopoProteo         | (7,)              |          0.1048 |         0.0116 |
| wgcna      | gat     |                                      8 |                                 0.1500 | torch_geometric.nn.models.GAT     | relu                 | nan                        |                   0.1000 |                 4.0000 |                           8.0000 |                    nan      |                       8.0000 |                   nan      |                      2.0000 | topobench.nn.wrappers.GNNWrapper      |                                     8 | GNNWrapper                            | topobench.nn.encoders.AllCellFeatureEncoder | AllCellFeatureEncoder                | (1,)                                |                                    8 |                               0.0000 | relu                   | (8, 4, 2)              |                     0.1000 |                            8 |                                   8 | 32                                |                      29336 |                      8.0000 |                     nan      |               968997 |                   968997 |                    0.0010 |                              0.0010 | /home/gbg141/TopoProteo         | /home/gbg141/TopoProteo         | (3,)              |          0.0951 |         0.0132 |
| wgcna      | gcn     |                                      8 |                                 0.2000 | torch_geometric.nn.models.GCN     | tanh                 | nan                        |                   0.3000 |               nan      |                           8.0000 |                    nan      |                       8.0000 |                   nan      |                      2.0000 | topobench.nn.wrappers.GNNWrapper      |                                     8 | GNNWrapper                            | topobench.nn.encoders.AllCellFeatureEncoder | AllCellFeatureEncoder                | (1,)                                |                                    8 |                               0.0000 | tanh                   | (16, 8, 4)             |                     0.1000 |                            8 |                                   8 | 16                                |                      29336 |                      8.0000 |                     nan      |               499757 |                   499757 |                    0.0010 |                              0.0010 | /home/gbg141/TopoProteo         | /home/gbg141/TopoProteo         | (7,)              |          0.0894 |         0.0112 |
| ('dataset', '')   | ('GPS', 1)      | ('gat', 1)      | ('gcn', 1)      | ('mlp', 1)      |
|:------------------|:----------------|:----------------|:----------------|:----------------|
| pointcloud        | nan             | nan             | nan             | 0.0802 ± 0.0135 |
| wgcna             | 0.1048 ± 0.0116 | 0.0951 ± 0.0132 | 0.0894 ± 0.0112 | nan             |

In [3]:
best_configs

,dataset,model,dataset.dataloader_params.batch_size,dataset.loader.parameters.adj_thresh,model.backbone._target_,model.backbone.act,model.backbone.attn_type,model.backbone.dropout,model.backbone.heads,model.backbone.hidden_channels,...,model/params/trainable,optimizer.parameters.lr,optimizer.parameters.weight_decay,paths.root_dir,paths.work_dir,trainer.devices,mean_val_mae,std_val_mae,n_folds,config_key
1789,pointcloud,mlp,32,1.00,torch.nn.Identity,NaN,NaN,NaN,NaN,NaN,...,485399,0.010,0.001,/home/lcornelis/code/TopoProteo,/home/lcornelis/code/TopoProteo,"(6,)",0.080183,0.013460,5,"(pointcloud, mlp, 32, 1.0, torch.nn.Identity, ..."
4009,wgcna,GPS,8,1.00,topobench.nn.backbones.GPSEncoder,NaN,performer,0.4,2.0,NaN,...,508585,0.010,0.000,/home/gbg141/TopoProteo,/home/gbg141/TopoProteo,"(7,)",0.104804,0.011560,5,"(wgcna, GPS, 8, 1.0, topobench.nn.backbones.GP..."
4694,wgcna,gat,8,0.15,torch_geometric.nn.models.GAT,relu,NaN,0.1,4.0,8.0,...,968997,0.001,0.001,/home/gbg141/TopoProteo,/home/gbg141/TopoProteo,"(3,)",0.095066,0.013228,5,"(wgcna, gat, 8, 0.15, torch_geometric.nn.model..."
6352,wgcna,gcn,8,0.20,torch_geometric.nn.models.GCN,tanh,NaN,0.3,NaN,8.0,...,499757,0.001,0.001,/home/gbg141/TopoProteo,/home/gbg141/TopoProteo,"(7,)",0.089390,0.011216,5,"(wgcna, gcn, 8, 0.2, torch_geometric.nn.models..."

In [10]:
grouped

,dataset,model,dataset.dataloader_params.batch_size,dataset.loader.parameters.adj_thresh,model.backbone._target_,model.backbone.act,model.backbone.dropout,model.backbone.heads,model.backbone.hidden_channels,model.backbone_wrapper._target_,...,model.readout.hidden_dim,model.readout.in_channels,model.readout.use_features,model/params/total,model/params/trainable,optimizer.parameters.lr,trainer.devices,mean_val_mae,std_val_mae,n_folds
0,pointcloud,mlp,8,1.00,torch.nn.Identity,NaN,NaN,NaN,NaN,topobench.nn.wrappers.IdentityWrapper,...,7258,NaN,True,248534,248534,0.0001,[4],13.464873,3.711611,5
1,pointcloud,mlp,8,1.00,torch.nn.Identity,NaN,NaN,NaN,NaN,topobench.nn.wrappers.IdentityWrapper,...,7258,NaN,True,248534,248534,0.0010,[4],14.361258,2.852578,5
2,pointcloud,mlp,8,1.00,torch.nn.Identity,NaN,NaN,NaN,NaN,topobench.nn.wrappers.IdentityWrapper,...,7258,NaN,True,484486,484486,0.0001,[4],14.009069,3.502408,5
3,pointcloud,mlp,8,1.00,torch.nn.Identity,NaN,NaN,NaN,NaN,topobench.nn.wrappers.IdentityWrapper,...,7258,NaN,True,484486,484486,0.0010,[4],14.775785,4.044234,5
4,pointcloud,mlp,8,1.00,torch.nn.Identity,NaN,NaN,NaN,NaN,topobench.nn.wrappers.IdentityWrapper,...,7258,NaN,True,250078,250078,0.0001,[4],13.042666,3.754864,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
441,wgcna,GATv4,8,0.25,topobench.nn.backbones.GATv4,relu,0.4,"[3, 3]","[16, 32]",topobench.nn.wrappers.GATv4Wrapper,...,21774,"[16, 32]",False,744574,744574,0.0010,[7],15.534735,4.831122,5
442,wgcna,GATv4,8,0.25,topobench.nn.backbones.GATv4,relu,0.4,"[3, 3]","[8, 16]",topobench.nn.wrappers.GATv4Wrapper,...,21774,"[8, 16]",False,387910,387910,0.0010,[6],17.038696,4.204840,5
443,wgcna,GATv4,8,0.25,topobench.nn.backbones.GATv4,relu,0.4,"[3, 3]","[8, 16]",topobench.nn.wrappers.GATv4Wrapper,...,21774,"[8, 16]",False,736438,736438,0.0010,[7],20.335993,2.029063,5
444,wgcna,GATv4,8,0.30,topobench.nn.backbones.GATv4,relu,0.4,"[3, 3]","[16, 32]",topobench.nn.wrappers.GATv4Wrapper,...,21774,"[16, 32]",False,744574,744574,0.0010,[7],17.755489,3.967473,4
445,wgcna,GATv4,8,0.30,topobench.nn.backbones.GATv4,relu,0.4,"[3, 3]","[8, 16]",topobench.nn.wrappers.GATv4Wrapper,...,21774,"[8, 16]",False,736438,736438,0.0010,[7],19.679412,1.384224,4

In [9]:
best_configs.iloc[1]

dataset                                                                             wgcna
model                                                                               GATv4
dataset.dataloader_params.batch_size                                                    2
dataset.loader.parameters.adj_thresh                                                  0.2
model.backbone.hidden_channels                                                  [64, 128]
model.backbone.in_channels                                                              8
model.backbone_wrapper.out_channels                                             [64, 128]
model.feature_encoder.out_channels                                                      8
model.readout.fc_dim                                                        [128, 64, 32]
model.readout.fc_input_dim                                                      [64, 128]
model.readout.graph_encoder_dim                                                       128
model.readout.in_channels                                                       [64, 128]
model/params/total                                                                3044982
model/params/trainable                                                            3044982
optimizer.parameters.lr                                                            0.0001
trainer.devices                                                                       [7]
mean_val_mae                                                                    11.998368
std_val_mae                                                                      5.932412
n_folds                                                                                 5
config_key                              (wgcna, GATv4, 2, 0.2, [64, 128], 8, [64, 128]...
Name: 1, dtype: object

In [ ]:
best_configs

IndexError: single positional indexer is out-of-bounds

In [23]:
best_configs["config_key"][5]

('wgcna',
 'mlp',
 8,
 0.2,
 'torch.nn.Identity',
 nan,
 nan,
 nan,
 'topobench.nn.wrappers.IdentityWrapper',
 1,
 'IdentityWrapper',
 'topobench.nn.encoders.IdentityEncoder',
 'IdentityEncoder',
 '1',
 1,
 'tanh',
 '[1024, 1024, 512, 256]',
 1,
 '[512, 256]',
 7258,
 nan,
 6022110,
 6022110,
 0.0001,
 '[7]')

In [36]:
best_configs["config_key"][2]

('spearman_correlation',
 'mlp',
 8,
 0.6,
 'torch.nn.Identity',
 nan,
 nan,
 nan,
 'topobench.nn.wrappers.IdentityWrapper',
 1,
 'IdentityWrapper',
 'topobench.nn.encoders.IdentityEncoder',
 'IdentityEncoder',
 '1',
 1,
 'tanh',
 '[1024, 1024, 512, 256]',
 1,
 '[512, 256]',
 7258,
 nan,
 6022110,
 6022110,
 0.0001,
 '[6]')